spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mqc520


    #定位mapper文件的位置com/cibei/springbootmybatistransaction/persistence/mapper
mybatis:
  mapper-locations: classpath*:com/cibei/springbootmybatistransaction/persistence/mapper/xml/*Mapper.xml
  #type-aliases-package:
  type-aliases-package: com.cibei.springbootmybatistransaction.persistence.entity