spring:
  redis:
    host: localhost
    port: 6379
    #password:
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 1
    timeout: 500





#    spring.redis.host=localhost
#    spring.redis.port=6379
#    #spring.redis.password=
#    spring.redis.database=1
#    spring.redis.pool.max-active=8
#    spring.redis.pool.max-wait=-1
#    spring.redis.pool.max-idle=500
#    spring.redis.pool.min-idle=0
#    spring.redis.timeout=0
